# Generated by Django 3.2.8 on 2021-10-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True, verbose_name='sitename')),
                ('logo', models.ImageField(null=True, upload_to='img/', verbose_name='logo')),
                ('homepage', models.CharField(max_length=100, null=True, verbose_name='Home')),
                ('About', models.CharField(max_length=100, null=True, verbose_name='About')),
                ('Services', models.CharField(max_length=100, null=True, verbose_name='Services')),
                ('Blog', models.CharField(max_length=100, null=True, verbose_name='Blog')),
                ('Contact', models.CharField(max_length=100, null=True, verbose_name='Contact')),
                ('Photo_Gallery', models.CharField(max_length=100, null=True, verbose_name='Photo')),
                ('name_ft', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('title_ft', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('description_ft', models.TextField(max_length=3000, null=True, verbose_name='description')),
                ('image_ft', models.ImageField(null=True, upload_to='img/', verbose_name='image')),
                ('fac_link', models.URLField(max_length=300, null=True, verbose_name='facbook')),
                ('twi_link', models.URLField(max_length=300, null=True, verbose_name='twitter')),
                ('gma_link', models.URLField(max_length=300, null=True, verbose_name='gmail')),
                ('ins_link', models.URLField(max_length=300, null=True, verbose_name='instgram')),
                ('yout_link', models.URLField(max_length=300, null=True, verbose_name='youtube')),
                ('crated_by', models.URLField(max_length=300, null=True, verbose_name='auther')),
                ('contect_us', models.CharField(max_length=300, null=True, verbose_name='contect')),
                ('phone', models.IntegerField(null=True, verbose_name='phone')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='url')),
            ],
        ),
    ]
