# Generated by Django 3.2.8 on 2021-10-26 22:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='phone'),
        ),
    ]
