# Generated by Django 3.2.8 on 2021-10-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fotter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=3000, verbose_name='description')),
                ('image', models.ImageField(upload_to='setting/', verbose_name='image')),
                ('fac_link', models.URLField(max_length=300, verbose_name='facbook')),
                ('slug', models.SlugField(null=True, verbose_name='url')),
                ('twi_link', models.URLField(max_length=300, verbose_name='twitter')),
                ('gma_link', models.URLField(max_length=300, verbose_name='gmail')),
                ('ins_link', models.URLField(max_length=300, verbose_name='instgram')),
                ('yout_link', models.URLField(max_length=300, verbose_name='youtube')),
                ('crated_by', models.URLField(max_length=300, verbose_name='auther')),
                ('contect_us', models.CharField(max_length=300, verbose_name='contect')),
                ('phone', models.IntegerField(verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='imagelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('images', models.ImageField(upload_to='setting/', verbose_name='image')),
                ('video_id', models.FileField(upload_to='setting/', verbose_name='video')),
                ('slug', models.SlugField(null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=300, verbose_name='sitename')),
                ('image_logo', models.ImageField(upload_to='setting/', verbose_name='image')),
                ('homepage', models.CharField(max_length=100, verbose_name='Home')),
                ('About', models.CharField(max_length=100, verbose_name='About')),
                ('Services', models.CharField(max_length=100, verbose_name='Services')),
                ('Blog', models.CharField(max_length=100, null=True, verbose_name='Blog')),
                ('Contact', models.CharField(max_length=100, verbose_name='Contact')),
                ('Photo_Gallery', models.CharField(max_length=100, verbose_name='Photo')),
                ('slug', models.SlugField(null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='section_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=3000, verbose_name='description')),
                ('image', models.ImageField(upload_to='setting/', verbose_name='image')),
                ('slug', models.SlugField(null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='section_four',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=3000, verbose_name='description')),
                ('image', models.ImageField(upload_to='setting/', verbose_name='image')),
                ('slug', models.SlugField(null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='section_three',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=3000, verbose_name='description')),
                ('image', models.ImageField(upload_to='setting/', verbose_name='image')),
                ('button', models.CharField(max_length=100, verbose_name='button')),
                ('slug', models.SlugField(null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='subservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(max_length=3000, verbose_name='description')),
                ('button_name', models.CharField(max_length=100, verbose_name='button_name')),
                ('slug', models.SlugField(null=True, verbose_name='url')),
            ],
        ),
    ]
