# Generated by Django 3.2.8 on 2021-10-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotter',
            name='contect_us',
            field=models.CharField(max_length=300, null=True, verbose_name='contect'),
        ),
        migrations.AlterField(
            model_name='fotter',
            name='crated_by',
            field=models.URLField(max_length=300, null=True, verbose_name='auther'),
        ),
        migrations.AlterField(
            model_name='fotter',
            name='description',
            field=models.TextField(max_length=3000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='fotter',
            name='fac_link',
            field=models.URLField(max_length=300, null=True, verbose_name='facbook'),
        ),
        migrations.AlterField(
            model_name='fotter',
            name='gma_link',
            field=models.URLField(max_length=300, null=True, verbose_name='gmail'),
        ),
        migrations.AlterField(
            model_name='fotter',
            name='image',
            field=models.ImageField(null=True, upload_to='setting/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='fotter',
            name='ins_link',
            field=models.URLField(max_length=300, null=True, verbose_name='instgram'),
        ),
        migrations.AlterField(
            model_name='fotter',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='fotter',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='fotter',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='fotter',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='fotter',
            name='twi_link',
            field=models.URLField(max_length=300, null=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='fotter',
            name='yout_link',
            field=models.URLField(max_length=300, null=True, verbose_name='youtube'),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='images',
            field=models.ImageField(null=True, upload_to='setting/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='video_id',
            field=models.FileField(null=True, upload_to='setting/', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='About',
            field=models.CharField(max_length=100, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='Contact',
            field=models.CharField(max_length=100, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='Photo_Gallery',
            field=models.CharField(max_length=100, null=True, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='Services',
            field=models.CharField(max_length=100, null=True, verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='homepage',
            field=models.CharField(max_length=100, null=True, verbose_name='Home'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='image_logo',
            field=models.ImageField(null=True, upload_to='setting/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='site_name',
            field=models.CharField(max_length=300, null=True, verbose_name='sitename'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='section_blog',
            name='description',
            field=models.TextField(max_length=3000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section_blog',
            name='image',
            field=models.ImageField(null=True, upload_to='setting/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='section_blog',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='section_blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='section_blog',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='section_four',
            name='description',
            field=models.TextField(max_length=3000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section_four',
            name='image',
            field=models.ImageField(null=True, upload_to='setting/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='section_four',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='section_four',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='section_four',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='section_three',
            name='button',
            field=models.CharField(max_length=100, null=True, verbose_name='button'),
        ),
        migrations.AlterField(
            model_name='section_three',
            name='description',
            field=models.TextField(max_length=3000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section_three',
            name='image',
            field=models.ImageField(null=True, upload_to='setting/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='section_three',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='section_three',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='section_three',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='button_name',
            field=models.CharField(max_length=100, null=True, verbose_name='button_name'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='description',
            field=models.TextField(max_length=3000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='url'),
        ),
    ]
