# Generated by Django 3.2.8 on 2021-10-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20211019_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelist',
            name='images',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='video_id',
            field=models.FileField(null=True, upload_to='media/', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='image_logo',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='image'),
        ),
    ]
