# Generated by Django 3.2.8 on 2021-10-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_auto_20211019_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelist',
            name='images',
        ),
        migrations.RemoveField(
            model_name='imagelist',
            name='video_id',
        ),
        migrations.AddField(
            model_name='imagelist',
            name='image',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='imagelist',
            name='video',
            field=models.FileField(null=True, upload_to='vid/', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='fotter',
            name='image',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='section_blog',
            name='image',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='section_four',
            name='image',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='section_three',
            name='image',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='image'),
        ),
    ]
