# Generated by Django 3.2.8 on 2021-10-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_auto_20211021_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelist',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='vid/', verbose_name='video'),
        ),
    ]
