# Generated by Django 3.2.8 on 2021-10-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_alter_imagelist_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbar',
            old_name='image_logo',
            new_name='logo',
        ),
    ]
