# Generated by Django 3.2.8 on 2021-10-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_rename_image_logo_navbar_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='logo',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='logo'),
        ),
    ]
