# Generated by Django 3.2.8 on 2021-10-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_alter_navbar_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fotter',
        ),
        migrations.DeleteModel(
            name='navbar',
        ),
    ]
